# SearXNG limiter config. We disable rate-limiting because the only client is us.
# (Public-facing instances should keep these enabled.)

[real_ip]
x_for = 0
ipv4_prefix = 32
ipv6_prefix = 128

[botdetection.ip_limit]
filter_link_local = false
link_token = false

[botdetection.ip_lists]
block_ip = []
pass_ip = ["127.0.0.0/8", "::1/128", "172.16.0.0/12"]
